
#╭━━━╮╱╱╱╱╱╱╱╱╱╱╱╱╱╭━━━╮╱╱╱╱╱╭━┳╮╭━━━╮
#╰╮╭╮┃╱╱╱╱╱╱╱╱╱╱╱╱╱┃╭━╮┃╱╱╱╱╱┃╭╯╰┫╭━╮┃
#╱┃┃┃┣━┳━━┳━━┳━━┳━╮┃┃╱╰╋━┳━━┳╯╰╮╭┫┃╱╰╋━━┳━┳━━╮
#╱┃┃┃┃╭┫╭╮┃╭╮┃╭╮┃╭╮┫┃╱╭┫╭┫╭╮┣╮╭┫┃┃┃╱╭┫╭╮┃╭┫┃━┫
#╭╯╰╯┃┃┃╭╮┃╰╯┃╰╯┃┃┃┃╰━╯┃┃┃╭╮┃┃┃┃╰┫╰━╯┃╰╯┃┃┃┃━┫
#╰━━━┻╯╰╯╰┻━╮┣━━┻╯╰┻━━━┻╯╰╯╰╯╰╯╰━┻━━━┻━━┻╯╰━━╯
#╱╱╱╱╱╱╱╱╱╭━╯┃
#╱╱╱╱╱╱╱╱╱╰━━╯

#Pomoc
bungee:
  ip: 127.0.0.1
  kick_message: "&e&lDragon&6&lCraft &e» &cWejdź przez IP: DCRFT.PL"
server:
  name: "s16"
  supported_versions:
    - 735
    - 736
    - 751
    - 753
    - 754
redchat:
- W?a?ciciel
greenchat:
- Moderator
filters:
  kurwa: (ಠ益ಠ)
  <3: ❤
  ogolem: ogółem
replacement:
  - ❤
afk:
  kick_warn_delay: 14
  kick_delay: 15
  sound_on_get_warn: true
  sound_on_notafk: true
shop_purchase:
  sound: "ENTITY_PLAYER_LEVELUP"
broadcast:
  cooldown: 90
staff:
  - NickNickerYT
  - JaneQ
  - MikiIgi192
  - kalkulator888
commands:
  vip: "/warp vip"
  svip: "/warp svip"
  mvip: "/warp mvip"
  evip: "/warp evip"
aliases:
  test: "/warp test"
disabled_default_permission: "cb.adm"
timedpermission: "essentials.kits.plus"
death_head_chance: 0.25