
#╭━━━╮╱╱╱╱╱╱╱╱╱╱╱╱╱╭━━━╮╱╱╱╱╱╭━┳╮╭━━━╮
#╰╮╭╮┃╱╱╱╱╱╱╱╱╱╱╱╱╱┃╭━╮┃╱╱╱╱╱┃╭╯╰┫╭━╮┃
#╱┃┃┃┣━┳━━┳━━┳━━┳━╮┃┃╱╰╋━┳━━┳╯╰╮╭┫┃╱╰╋━━┳━┳━━╮
#╱┃┃┃┃╭┫╭╮┃╭╮┃╭╮┃╭╮┫┃╱╭┫╭┫╭╮┣╮╭┫┃┃┃╱╭┫╭╮┃╭┫┃━┫
#╭╯╰╯┃┃┃╭╮┃╰╯┃╰╯┃┃┃┃╰━╯┃┃┃╭╮┃┃┃┃╰┫╰━╯┃╰╯┃┃┃┃━┫
#╰━━━┻╯╰╯╰┻━╮┣━━┻╯╰┻━━━┻╯╰╯╰╯╰╯╰━┻━━━┻━━┻╯╰━━╯
#╱╱╱╱╱╱╱╱╱╭━╯┃
#╱╱╱╱╱╱╱╱╱╰━━╯

#Pomoc
server:
  name: "s16"
  type: survival
chatformat:
  w?a?ciciel: "§c"
  admin: "§c"
  viceadministrator: "§e"
  pomocnik: "§a"
  moderator: "§a"
  opiekun: "§d"
filters:
  kurwa: (ಠ益ಠ)
  <3: ❤
  ogolem: ogółem
replacement:
  - ❤
afk:
  kick_warn_delay: 14
  kick_delay: 15
  sound_on_get_warn: true
  sound_on_notafk: true
shop_purchase:
  sound: "ENTITY_PLAYER_LEVELUP"
broadcast:
  cooldown: 90
hologram:
  cooldown: 5
  x: 0
  y: 0
  z: 0
staff:
  - NickNickerYT
  - JaneQ
  - MikiIgi192
  - kalkulator888
commands:
  vip: "/warp vip"
  svip: "/warp svip"
  mvip: "/warp mvip"
  evip: "/warp evip"
aliases:
  test: "/warp test"
disabled_default_permission: "cb.adm"
timedpermission: "essentials.kits.plus"
death_head_chance: 0.25
vote_ip: "dcrft.pl"
kits:
  example:
    item: CHEST
    name: "§6§nExampleKit"
marry_warp: "slub"
marry_item:
  material: DRAGON_EGG
  amount: 1
  name: "§6§nSmocze jajo"
  enchantment:
    enchantment: THORNS
    level: 10
  lore:
  - "§aCenna waluta poszukiwana przez wiele osób."