main: pl.dcrft.DragonCraftCore
name: ${project.name}
version: ${project.version}-b${buildNumber}
author: NickNickerYT
loadbefore: [AdvancedBan, Vault, PlaceholderAPI]
softdepend: [LuckPerms]
description: DragonCraftCore - the core which fits the DragonCraft needs. The core plugin created for DragonCraft Minecraft server that provides basic features for DragonCraft. Built on ${timestamp}
api-version: 1.16
commands:
  pomoc:
    description: Wyświetl pomoc.
    usage: /pomoc
  dcc:
    description: Komenda główna DragonCraftCore.
    usage: /dcc [<przeladuj>]
  cc:
    description: Czyszczenie czatu.
    usage: /cc
  czat:
    description: Przełaczanie czatu.
  losuj:
    description: Losowanie kolorków.
    usage: /losuj
  restart:
    description: Restartuje serwer za minutę.
    usage: /restart60
  reload:
    description: Przeładowuje serwer za minutę.
    usage: /reload60
  stop:
    description: Zatrzumuje serwer za minutę.
    usage: /stop60
  przerwa:
    description: Rozpoczyna przerwę techniczną za minutę.
    usage: /przerwa60
  sklepbroadcast:
    description: Ogłasza zakup ze sklepu.
    usage: /sklepbroadcast [gracz] [tekst]
  sklepbroadcastdonate:
    description: Ogłasza dotację ze sklepu.
    usage: /sklepbroadcastdonate [gracz] [tekst]
  dcccast:
    description: Czyszczenie czatu.
    usage: /cc
  vip:
    description: Alias do /warp vip lub pokazanie możliwości VIPa w zależności od rangi.
    usage: /vip
  svip:
    description: Alias do /warp svip lub pokazanie możliwości SVIPa w zależności od rangi.
    usage: /svip
  mvip:
    description: Alias do /warp mvip lub pokazanie możliwości MVIPa w zależności od rangi.
    usage: /mvip
  evip:
    description: Alias do /warp evip lub pokazanie możliwości EVIPa w zależności od rangi.
    usage: /evip
  ac:
    description: Włącz AdminChat.
  mc:
    description: Włącz ModChat.
  stream:
    description: Włącza tryb streamu.
  gracz:
    description: Wyświetl statystyki gracza.
  warn:
    description: Ostrzeż gracza.
  checkwarn:
    description: Wyświetl ostrzeżenia gracza.
  slub:
    description: slub
  sakceptuj:
    description: sakceptuj
  sodrzuc:
    description: sodrzuc
  rozwod:
    description: no rozwod a co chciales
  znajomi:
    description: a po co komu to badziewie, no ale jest
  z:
    description: a po co komu to badziewie, no ale jest
  f:
    description: a po co komu to badziewie, no ale jest
  nieafk:
    description: aa
  alias:
    description: aliasy
  +:
    description: dlugosc plusa
  